<?php

namespace DoctrineORMModule\Proxy\__CG__\Produto\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ProdutoSubcategoria extends \Produto\Entity\ProdutoSubcategoria implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdsubcategoria()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idsubcategoria"];
        }
        $this->__load();
        return parent::getIdsubcategoria();
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function getCategorias()
    {
        $this->__load();
        return parent::getCategorias();
    }

    public function setIdsubcategoria($idsubcategoria)
    {
        $this->__load();
        return parent::setIdsubcategoria($idsubcategoria);
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function setCategorias($categorias)
    {
        $this->__load();
        return parent::setCategorias($categorias);
    }

    public function getProdutos()
    {
        $this->__load();
        return parent::getProdutos();
    }

    public function getSlugSubcategoria()
    {
        $this->__load();
        return parent::getSlugSubcategoria();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idsubcategoria', 'nome', 'slugSubcategoria', 'categorias', 'produtos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}