<?php

namespace DoctrineORMModule\Proxy\__CG__\Pagseguro\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UsuarioUsuarios extends \Pagseguro\Entity\UsuarioUsuarios implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getNivelUsuario()
    {
        $this->__load();
        return parent::getNivelUsuario();
    }

    public function setNivelUsuario($nivelUsuario)
    {
        $this->__load();
        return parent::setNivelUsuario($nivelUsuario);
    }

    public function getIdusuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idusuario"];
        }
        $this->__load();
        return parent::getIdusuario();
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function getSenha()
    {
        $this->__load();
        return parent::getSenha();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getDtCadastro()
    {
        $this->__load();
        return parent::getDtCadastro();
    }

    public function getDtAtivacao()
    {
        $this->__load();
        return parent::getDtAtivacao();
    }

    public function setIdusuario($idusuario)
    {
        $this->__load();
        return parent::setIdusuario($idusuario);
    }

    public function setLogin($login)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function setSenha($senha)
    {
        $this->__load();
        return parent::setSenha($senha);
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function setDtCadastro($dtCadastro)
    {
        $this->__load();
        return parent::setDtCadastro($dtCadastro);
    }

    public function setDtAtivacao($dtAtivacao)
    {
        $this->__load();
        return parent::setDtAtivacao($dtAtivacao);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idusuario', 'login', 'senha', 'email', 'dtCadastro', 'dtAtivacao', 'nivelUsuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}