<?php

namespace DoctrineORMModule\Proxy\__CG__\Produto\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ProdutoProdutos extends \Produto\Entity\ProdutoProdutos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdproduto()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idproduto"];
        }
        $this->__load();
        return parent::getIdproduto();
    }

    public function getTitulo()
    {
        $this->__load();
        return parent::getTitulo();
    }

    public function getValor()
    {
        $this->__load();
        return parent::getValor();
    }

    public function getProdutosubcategoria()
    {
        $this->__load();
        return parent::getProdutosubcategoria();
    }

    public function setIdproduto($idproduto)
    {
        $this->__load();
        return parent::setIdproduto($idproduto);
    }

    public function setTitulo($titulo)
    {
        $this->__load();
        return parent::setTitulo($titulo);
    }

    public function setValor($valor)
    {
        $this->__load();
        return parent::setValor($valor);
    }

    public function setProdutosubcategoria($produtosubcategoria)
    {
        $this->__load();
        return parent::setProdutosubcategoria($produtosubcategoria);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idproduto', 'titulo', 'slugProduto', 'valor', 'produtosubcategoria');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}