<!--Institucional-->

				<div id="Institucional">
					<div id="MenuInstitucional">
						<ul class="BoxMenuInstitucional">
							<li class="BoxMenuInstitucional">
								<a href="#tab_1" class="QuemSomos activetab_1" title="Quem Somos" onclick="mudarTab(1)">Quem Somos</a>
							</li>
							<li class="BoxMenuInstitucional">
								<a href="#tab_2" class="MapaSite" title="Mapa do Site" onclick="mudarTab(2)">Mapa do Site</a>
							</li>
							<li class="BoxMenuInstitucional">
								<a href="#tab_3" class="TermosPesquisa" title="Perguntas Frequentes" onclick="mudarTab(3)">Perguntas Frequentes</a>
							</li>
							<li class="BoxMenuInstitucional">
								<a href="#tab_4" class="TrocasDevolucoes" title="Trocas e Devoluções" onclick="mudarTab(4)">Trocas e Devoluções</a>
							</li>
							<li class="BoxMenuInstitucional">
								<a href="#tab_5" class="PoliticaPrivacidade" title="Política de Privacidade" onclick="mudarTab(5)">Política de Privacidade</a>
							</li>
							<li class="BoxMenuInstitucional">
								<a href="#tab_6" class="FaleConosco" title="Fale Conosco" onclick="mudarTab(6)">Fale Conosco</a>
							</li>		
						</ul>
					</div>

					<div id="tab_1" class="QuemSomos">
						<div id="BoxInstitucional">
							<h3 class="tt_Institucional">Quem somos</h3>
							<p class="txt_Institucional">O Café Seleto é uma das marcas de café mais famosas e queridas do Brasil. Também pudera. Além de ter um sabor todo especial, sempre contou com memoráveis campanhas publicitárias, e possui o jingle mais conhecido da história da propaganda brasileira. E esta grande marca está de volta ao mercado com força total. Comprada pelo Grupo Mex, o Café Seleto está de cara nova e trazendo muitas novidades também. As embalagens estão mais modernas, a campanha publicitária renovada e o café, ainda mais saboroso.</p>

							<h5 class="Sub_tt">Missão</h5>

							<p class="txt_Institucional">Produzir e fornecer produtos de qualidade, inovadores, competitivos e sustentáveis em um ambiente socialmente responsável.</p>

							<h5 class="Sub_tt">Visão</h5>

							<p class="txt_Institucional">Ser uma das mais conceituadas e competitivas empresas alimentícias da América do Sul, reconhecida pelas práticas de qualidade, sustentabilidade e inovação.</p>
						</div>
					</div>
					
					<div id="tab_2" class="MapaSite" style="display:none;">MapaSite</div>
					<div id="tab_3" class="TermosPesquisa" style="display:none;">TermosPesquisa</div>

					<div id="tab_4" class="TrocasDevolucoes" style="display:none;">
						<div id="BoxInstitucional">
							<h3 class="tt_Institucional">Política de trocas e devolução<br/>Seleto Alimentos</h3>
							<p class="txt_Institucional">Visando garantir total satisfação de nossos clientes e consumidores nossa política de trocas e devoluções está de acordo com o código de defesa do consumidor, preservando todos os seus direitos.</p>
							<p class="txt_Institucional">Portanto toda e qualquer ocorrência ou divergência, seja uma embalagem violada, produto avariado ou um pedido que chegou diferente do solicitado, recuse o recebimento e contate-nos imediatamente. Caso já tenha recebido o produto e necessite fazer uma troca ou devolução é indispensável à apresentação da nota fiscal (que foi entregue junto com o produto). Também solicitamos a embalagem original, na qual o produto foi entregue.</p>
							<p class="txt_Institucional">A troca de produtos defeituosos devem seguir as mesmas condições descritas na devolução por arrependimento/desistência. O frete do retorno de produtos defeituosos será de responsabilidade do Seleto Alimentos.</p>
							<p class="txt_Institucional">O contato conosco pode ser feito pelo e-mail <a class="LinkTrocasDevolucoes" href="">sac.seletoalimentos@grupomex.com.br</a> ou pelo telefone <strong>(11) 3611-3869</strong>. Nosso horário de atendimento por telefone é de segunda a sexta-feira das 8:30 as 12:30h e das 13:30 as17h.</p> 
							<p class="txt_Institucional">Enviaremos os melhores esforços para que tudo seja resolvido o mais rápido possível.</p>
						</div>
					</div>

					<div id="tab_5" class="PoliticaPrivacidade" style="display:none;">
						<div id="BoxInstitucional">
							<h3 class="tt_Institucional">Politica Privacidade</h3>
							<h5 class="Sub_tt">Objetivo</h5>
							<p class="txt_Institucional">Nossa Política de privacidade tem como objetivo definir e evidenciar nosso compromisso em garantir a proteção das informações coletadas dos usuários. Esses dados são importantes porque nos ajudam a tornar este site melhor e cada vez mais direcionado a você, usuário.</p>
							<h5 class="Sub_tt">Compromisso de confidencialidade</h5>
							<p class="txt_Institucional">Todas as informações dos usuários do site, inclusive seu e-mail, não serão fornecidas para terceiros (salvo situação da limitação legal, conforme item a seguir). As informações de pagamento e comercialização fornecidas por você serão mantidas em sigilo e utilizadas exclusivamente pelo Café Canecão.</p>
							<h5 class="Sub_tt">Limitação legal do compromisso de confidencialidade</h5>
							<p class="txt_Institucional">As informações fornecidas pelos usuários poderão ser entregues às autoridades estabelecidas se por estas forem solicitados para condução de investigação criminal ou apuração de crimes de qualquer natureza em que o usuário figure como réu ou investigado.</p>
							<h5 class="Sub_tt">Manuseio das informações</h5>
							<p class="txt_Institucional">Todos os dados pessoais informados ao nosso site são armazenados em um banco de dados reservado e com acesso restrito. Os funcionários da Seleto Alimentos habilitados que tiverem acesso a esses dados para o exercício de suas atividades profissionais são obrigados, por contrato, a manter a confidencialidade das informações e são terminantemente proibidos de utilizá-los indevidamente.</p>
							<h5 class="Sub_tt">Responsabilidade comercial</h5>
							<p class="txt_Institucional">A Loja Seleto Alimentos é responsável pelos produtos que vende e que se obriga(m) a cumprir as exigências da lei, inclusive no que se refere à proteção aos direitos do consumidor. Exija sempre a nota fiscal. Antes de usufruir de nossos serviços leia atentamente nosso Termo de Uso. Caso não esteja de acordo, por favor, não os utilize.</p>
							<h5 class="Sub_tt">E-mail marketing</h5>
							<p class="txt_Institucional">Nossas campanhas de e-mail marketing respeitam a política anti-spam e nossos informativos permitem o descadastramento de seu e-mail. Nesses e-mails não serão solicitadas confirmação de dados, cadastro e alteração/confirmação de senha. Também não serão enviados arquivos (executáveis ou não) anexados.</p>
							<h5 class="Sub_tt">Segurança</h5>
							<p class="txt_Institucional">O sistema de vendas do site foi planejado para garantir a privacidade das informações relativas a cartão de crédito, nome, residência, correio eletrônico e qualquer outra informação que o cliente tenha fornecido.</p>
						</div>

					</div>


					<div id="tab_6" class="FaleConosco" style="display:none;">
						<div id="BoxInstitucional">
							<h3 class="tt_Institucional">Fale conosco</h3>
							<p class="txt_Institucional">Dúvidas, sugestões ou reclamações.</p><br/>
				              <form class="FormInstitucional" action="">
				                   <label class="tt_FormInstitucional">Nome:</label><br/>
				                   <input type="text" class="NomeFormInst" value=""><br/>
				                   <label class="tt_FormInstitucional">E-mail:</label><br/>
				                   <input type="text" class="EmailFormInst" value=""><br/>
				                   <label class="tt_FormInstitucional">Telefone:</label><br/>
				                   <input type="text" class="TelefoneFormInst" value=""><br/>
				                   <label class="tt_FormInstitucional">Destinatário:</label><br/>
				                   <select class="DestinatarioFormInst">
                                   <option>Selecione</option>
                                   </select><br/>
				                   <label class="tt_FormInstitucional">Mensagem:</label><br/>
				                   <textarea class="AreaFormInstitucional" name="mensagem"></textarea><br/>
				                   <input type="reset" value="Limpar" class="LimparFormInst">	
				                   <input type="submit" value="Enviar" class="EnviarFormInst">
				              </form>
						</div>
					</div>
				</div>
				<!--Fim Institucional-->